### PR TITLE
feature4 added - admin panel link

### PR DESCRIPTION
**Pull request by krzysiekpom**
> Admin can see a link "navigate to the admin panel" somewhere on the page. He can click the link to display that page (accessible only by admins). Do not use rails_admin or similar gems.

credentials as usual

### CODE REVIEW

**Comment by krzysiekpom** [comment]
Should the feature branches be merged into base branches or master? I have merged PR feature2 into feature1 and am wondering whether it was the right approach.

**Comment by socjopata** [comment]
If the base (feature) branch has been already merged to master you should rebase with master and merge to master instead

**Comment by krzysiekpom** [comment]
Hm, ok. One more question - "merge" in this case is "merge pull request on GH" or pushing directly from local repo? Currently all PRs have other feature branches as base branch, therefore for me it feels like the changes will never apply into master. Should I push from local master, change the base branch or am I missing something? Sorry for these questions, but I've got to admit that most of git (especially PR) was black magic to me one week ago. Obviously I'm not there yet, but at least I can follow logic that I didn't understand before. Thanks a lot.

**Comment by socjopata** [comment]
You don't have to use the GUI provided by github.com. Feel free to do everything on your local machine, using your shell, and then pushing your updates to the remote, if that makes more sense / is more convenient for you. If you do it right, this PR will change it's status to "merged" automagically.

**Comment by krzysiekpom** [comment]
Awesome, thanks.

**Pull request merged**
